<?php

namespace Depot\BaseBundle\Repository;
use Depot\BaseBundle\Entity\Depotstate;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * DepotstateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotstateRepository extends \Doctrine\ORM\EntityRepository
{
	public function querysearch($site,$dstate)
	{
		return $this->getEntityManager()
            ->createQuery('
                SELECT ds
                FROM DepotBaseBundle:Depotstate ds JOIN DepotBaseBundle:Depot d
                WHERE d.id=ds.deid AND d.site = :site AND ds.state = :dstate
                ORDER BY ds.itime DESC
            ')->setParameter('site', $site)->setParameter('dstate', $dstate)
        ;
	}

	public function page($site,$dstate,$page = 1)
	{
		$paginator = new Pagerfanta(new DoctrineORMAdapter($this->querysearch($site,$dstate), false));
        $paginator->setMaxPerPage(Depotstate::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
	}

    public function gstatis($conn,$web)
    {
        return $conn->fetchAll('
                SELECT DATE_FORMAT(a.itime,\'%Y-%m\') AS day
                ,(SELECT sum(b.num) FROM depotstate as b WHERE DATE_FORMAT(b.itime, \'%Y-%m\') =day AND b.deid IN (SELECT e.id FROM depot as e WHERE e.site = \''.$web.'\') AND state=1) AS innum
                ,(SELECT sum(c.num) FROM depotstate as c WHERE DATE_FORMAT(c.itime, \'%Y-%m\') =day AND c.deid IN (SELECT f.id FROM depot as f WHERE f.site = \''.$web.'\') AND state=2) AS outnum
                ,(SELECT sum(d.num) FROM depotstate as d WHERE DATE_FORMAT(d.itime, \'%Y-%m\') =day AND d.deid IN (SELECT g.id FROM depot as g WHERE g.site = \''.$web.'\') AND state=0) AS delnum
                FROM depotstate as a
                WHERE DATE_FORMAT(itime,\'%Y-%m\') BETWEEN \''.date('Y',time()).'-01\' AND \''.(date('Y',time())+1).'-01\' AND a.deid IN (SELECT id FROM depot WHERE site = \''.$web.'\')
                GROUP BY day ORDER BY day ASC
            ')
        ;
    }

    public function gdepotdata($conn,$web)
    {
        return $conn->fetchAll('
                SELECT b.name
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-01" AND "'.date('Y',time()).'-03" AND deid=a.deid AND state=1 ) AS oneinnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-01" AND "'.date('Y',time()).'-03" AND deid=a.deid AND state=1 ) AS oneinprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-01" AND "'.date('Y',time()).'-03" AND deid=a.deid AND state=2 ) AS oneoutnum
                ,(SELECT sum(num*(sellprice-baseprice)) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-01" AND "'.date('Y',time()).'-03" AND deid=a.deid AND state=2 ) AS oneoutprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-01" AND "'.date('Y',time()).'-03" AND deid=a.deid AND state=0 ) AS onedelnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-01" AND "'.date('Y',time()).'-03" AND deid=a.deid AND state=0 ) AS onedelprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-04" AND "'.date('Y',time()).'-06" AND deid=a.deid AND state=1 ) AS twoinnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-04" AND "'.date('Y',time()).'-06" AND deid=a.deid AND state=1 ) AS twoinprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-04" AND "'.date('Y',time()).'-06" AND deid=a.deid AND state=2 ) AS twooutnum
                ,(SELECT sum(num*(sellprice-baseprice)) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-04" AND "'.date('Y',time()).'-06" AND deid=a.deid AND state=2 ) AS twooutprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-04" AND "'.date('Y',time()).'-06" AND deid=a.deid AND state=0 ) AS twodelnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\')="'.date('Y',time()).'-02" AND deid=a.deid AND state=0 ) AS twodelprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-07" AND "'.date('Y',time()).'-09" AND deid=a.deid AND state=1 ) AS threeinnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-07" AND "'.date('Y',time()).'-09" AND deid=a.deid AND state=1 ) AS threeinprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-07" AND "'.date('Y',time()).'-09" AND deid=a.deid AND state=2 ) AS threeoutnum
                ,(SELECT sum(num*(sellprice-baseprice)) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-07" AND "'.date('Y',time()).'-09" AND deid=a.deid AND state=2 ) AS threeoutprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-07" AND "'.date('Y',time()).'-09" AND deid=a.deid AND state=0 ) AS threedelnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-07" AND "'.date('Y',time()).'-09" AND deid=a.deid AND state=0 ) AS threedelprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-10" AND "'.date('Y',time()).'-12" AND deid=a.deid AND state=1 ) AS fourinnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-10" AND "'.date('Y',time()).'-12" AND deid=a.deid AND state=1 ) AS fourinprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-10" AND "'.date('Y',time()).'-12" AND deid=a.deid AND state=2 ) AS fouroutnum
                ,(SELECT sum(num*(sellprice-baseprice)) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-10" AND "'.date('Y',time()).'-12" AND deid=a.deid AND state=2 ) AS fouroutprice
                ,(SELECT sum(num) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-10" AND "'.date('Y',time()).'-12" AND deid=a.deid AND state=0 ) AS fourdelnum
                ,(SELECT sum(num*baseprice) FROM depotstate WHERE DATE_FORMAT(itime, \'%Y-%m\') BETWEEN "'.date('Y',time()).'-10" AND "'.date('Y',time()).'-12" AND deid=a.deid AND state=0 ) AS fourdelprice
                FROM depotstate as a
                LEFT JOIN depot AS b ON a.deid=b.id
                WHERE DATE_FORMAT(itime,\'%Y-%m\') BETWEEN \''.date('Y',time()).'-01\' AND \''.(date('Y',time())+1).'-01\' AND b.site = \''.$web.'\'
                GROUP BY a.deid ORDER BY a.deid ASC
            ')
        ;
    }
}