<?php

namespace Depot\BaseBundle\Repository;
use Depot\BaseBundle\Entity\Depot;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends \Doctrine\ORM\EntityRepository
{
	public function querysearch($site)
	{
		return $this->getEntityManager()
            ->createQuery('
                SELECT d
                FROM DepotBaseBundle:Depot d
                WHERE d.site = :site
                ORDER BY d.id DESC
            ')->setParameter('site', $site)
        ;
	}

	public function page($site,$page = 1)
	{
		$paginator = new Pagerfanta(new DoctrineORMAdapter($this->querysearch($site), false));
        $paginator->setMaxPerPage(Depot::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
	}

}
