<?php

namespace User\ToolBundle\Repository;

/**
 * ToolbuyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolbuyRepository extends \Doctrine\ORM\EntityRepository
{
}
