<?php

namespace User\ToolBundle\Repository;

/**
 * TooltotypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TooltotypeRepository extends \Doctrine\ORM\EntityRepository
{
}
