<?php

namespace User\ToolBundle\Repository;

/**
 * TooltypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TooltypeRepository extends \Doctrine\ORM\EntityRepository
{
}
