<?php

namespace User\ToolBundle\Repository;
use User\ToolBundle\Entity\Tool;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ToolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolRepository extends \Doctrine\ORM\EntityRepository
{
	public function querysearch()
	{
		return $this->getEntityManager()
            ->createQuery('
                SELECT t
                FROM UserToolBundle:Tool t
                ORDER BY t.recommend DESC
            ');
	}

	public function page($page = 1)
	{
		$paginator = new Pagerfanta(new DoctrineORMAdapter($this->querysearch(), false));
        $paginator->setMaxPerPage(Tool::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
	}

}
