<?php

namespace User\ToolBundle\Repository;

/**
 * ToolsiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToolsiteRepository extends \Doctrine\ORM\EntityRepository
{
}
