<?php

namespace User\SiteBundle\Repository;
use User\SiteBundle\Entity\Fodder;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * FodderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FodderRepository extends \Doctrine\ORM\EntityRepository
{
	public function querysearch()
	{
		return $this->getEntityManager()
            ->createQuery('
                SELECT f
                FROM UserSiteBundle:Fodder f
                ORDER BY f.id DESC
            ')
        ;
	}

	public function page($page = 1)
	{
		$paginator = new Pagerfanta(new DoctrineORMAdapter($this->querysearch(), false));
        $paginator->setMaxPerPage(Fodder::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
	}

}
