<?php

namespace User\SiteBundle\Repository;
use User\SiteBundle\Entity\Sitepost;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * SitepostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitepostRepository extends \Doctrine\ORM\EntityRepository
{
	public function querysearch($site)
	{
		return $this->getEntityManager()
            ->createQuery('
                SELECT s
                FROM UserSiteBundle:Sitepost s
                WHERE s.site = :site
                ORDER BY s.sort DESC,s.id DESC
            ')->setParameter('site', $site)
        ;
	}

	public function page($site,$page = 1)
	{
		$paginator = new Pagerfanta(new DoctrineORMAdapter($this->querysearch($site), false));
        $paginator->setMaxPerPage(Sitepost::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
	}

}
