# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Admin\BaseBundle\Entity\Aduser: bcrypt
        User\BaseBundle\Entity\User: bcrypt

    providers:
        admin_users:
            entity: { class: AdminBaseBundle:Aduser, property: username }
        users_info:
            entity: { class: UserBaseBundle:User, property: username }

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    # providers:
    #     in_memory:
    #         memory: ~

    firewalls:
        admin_area:
            pattern: ^/admin
            anonymous: true
            provider: admin_users
            context: aduser
            form_login:
                login_path: ad_login
                check_path: ad_land
                username_parameter: username
                password_parameter: password
                csrf_parameter: _token
                csrf_token_id: adlandcsrf
                csrf_token_generator: security.csrf.token_manager
                post_only: true
            logout:
                path: ad_logout
                target: index
            access_denied_url: adnodenied

        user_area:
            #pattern: /(user|tool|site)?
            pattern: /(?!(admin|help|api))
            anonymous: true
            provider: users_info
            context: user
            form_login:
                login_path: login
                check_path: land
                username_parameter: username
                password_parameter: password
                csrf_parameter: _token
                csrf_token_id: userlandcsrf
                csrf_token_generator: security.csrf.token_manager
                post_only: true
            logout:
                path: logout
                target: index
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
            access_denied_url: nodenied

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
    access_control:
        - { path: ^/admin/adlogin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/adland, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /(login|land|register|forpsw|respsw), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: /(user|site|tool|depot), roles: ROLE_USER }
        # disables authentication for assets and the profiler, adapt it according to your needs
        # dev:
        #     pattern: ^/(_(profiler|wdt)|css|images|js)/
        #     security: false

        # main:
        #     anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
